### ISSUE TITLE
Icon/Logo Proposal

### ISSUE THREAD

**Issue by loydjayme25** [webianks/BlueChat#2]
hello sir @webianks  , can i submit my design ?

**Comment by webianks** [comment]
Yes.

**Comment by loydjayme25** [comment]
how about these two designs @webianks 

first design was simple , i put the symbol of bluetooth as letter B. the second design was a little bit colorful , the background color was based on the Kotlin since the bluechat uses kotlin


![new](https://user-images.githubusercontent.com/37318022/41273523-69523d1c-6e4c-11e8-85e2-010e290d8945.png)

**Comment by webianks** [comment]
Hi, Thanks for the logos I am not planning to use them for now.
